// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Insurance is the predicate function for insurance builders.
type Insurance func(*sql.Selector)

// Rent is the predicate function for rent builders.
type Rent func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomStatus is the predicate function for roomstatus builders.
type RoomStatus func(*sql.Selector)

// RoomType is the predicate function for roomtype builders.
type RoomType func(*sql.Selector)

// Roomage is the predicate function for roomage builders.
type Roomage func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserStatus is the predicate function for userstatus builders.
type UserStatus func(*sql.Selector)
