// Code generated by entc, DO NOT EDIT.

package insurance

const (
	// Label holds the string label denoting the insurance type in the database.
	Label = "insurance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInsurance holds the string denoting the insurance field in the database.
	FieldInsurance = "insurance"

	// EdgeInsuranceRent holds the string denoting the insurancerent edge name in mutations.
	EdgeInsuranceRent = "InsuranceRent"

	// Table holds the table name of the insurance in the database.
	Table = "insurances"
	// InsuranceRentTable is the table the holds the InsuranceRent relation/edge.
	InsuranceRentTable = "rents"
	// InsuranceRentInverseTable is the table name for the Rent entity.
	// It exists in this package in order to avoid circular dependency with the "rent" package.
	InsuranceRentInverseTable = "rents"
	// InsuranceRentColumn is the table column denoting the InsuranceRent relation/edge.
	InsuranceRentColumn = "insurance_insurance_rent"
)

// Columns holds all SQL columns for insurance fields.
var Columns = []string{
	FieldID,
	FieldInsurance,
}
