// Code generated by entc, DO NOT EDIT.

package insurance

import (
	"github.com/PON/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Insurance applies equality check predicate on the "Insurance" field. It's identical to InsuranceEQ.
func Insurance(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsurance), v))
	})
}

// InsuranceEQ applies the EQ predicate on the "Insurance" field.
func InsuranceEQ(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInsurance), v))
	})
}

// InsuranceNEQ applies the NEQ predicate on the "Insurance" field.
func InsuranceNEQ(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInsurance), v))
	})
}

// InsuranceIn applies the In predicate on the "Insurance" field.
func InsuranceIn(vs ...int) predicate.Insurance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInsurance), v...))
	})
}

// InsuranceNotIn applies the NotIn predicate on the "Insurance" field.
func InsuranceNotIn(vs ...int) predicate.Insurance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Insurance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInsurance), v...))
	})
}

// InsuranceGT applies the GT predicate on the "Insurance" field.
func InsuranceGT(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInsurance), v))
	})
}

// InsuranceGTE applies the GTE predicate on the "Insurance" field.
func InsuranceGTE(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInsurance), v))
	})
}

// InsuranceLT applies the LT predicate on the "Insurance" field.
func InsuranceLT(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInsurance), v))
	})
}

// InsuranceLTE applies the LTE predicate on the "Insurance" field.
func InsuranceLTE(v int) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInsurance), v))
	})
}

// HasInsuranceRent applies the HasEdge predicate on the "InsuranceRent" edge.
func HasInsuranceRent() predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InsuranceRentTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InsuranceRentTable, InsuranceRentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInsuranceRentWith applies the HasEdge predicate on the "InsuranceRent" edge with a given conditions (other predicates).
func HasInsuranceRentWith(preds ...predicate.Rent) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InsuranceRentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InsuranceRentTable, InsuranceRentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Insurance) predicate.Insurance {
	return predicate.Insurance(func(s *sql.Selector) {
		p(s.Not())
	})
}
