// Code generated by entc, DO NOT EDIT.

package userstatus

import (
	"github.com/PON/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// UserStatus applies equality check predicate on the "UserStatus" field. It's identical to UserStatusEQ.
func UserStatus(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserStatus), v))
	})
}

// UserStatusEQ applies the EQ predicate on the "UserStatus" field.
func UserStatusEQ(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserStatus), v))
	})
}

// UserStatusNEQ applies the NEQ predicate on the "UserStatus" field.
func UserStatusNEQ(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserStatus), v))
	})
}

// UserStatusIn applies the In predicate on the "UserStatus" field.
func UserStatusIn(vs ...string) predicate.UserStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUserStatus), v...))
	})
}

// UserStatusNotIn applies the NotIn predicate on the "UserStatus" field.
func UserStatusNotIn(vs ...string) predicate.UserStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUserStatus), v...))
	})
}

// UserStatusGT applies the GT predicate on the "UserStatus" field.
func UserStatusGT(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserStatus), v))
	})
}

// UserStatusGTE applies the GTE predicate on the "UserStatus" field.
func UserStatusGTE(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserStatus), v))
	})
}

// UserStatusLT applies the LT predicate on the "UserStatus" field.
func UserStatusLT(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserStatus), v))
	})
}

// UserStatusLTE applies the LTE predicate on the "UserStatus" field.
func UserStatusLTE(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserStatus), v))
	})
}

// UserStatusContains applies the Contains predicate on the "UserStatus" field.
func UserStatusContains(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUserStatus), v))
	})
}

// UserStatusHasPrefix applies the HasPrefix predicate on the "UserStatus" field.
func UserStatusHasPrefix(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUserStatus), v))
	})
}

// UserStatusHasSuffix applies the HasSuffix predicate on the "UserStatus" field.
func UserStatusHasSuffix(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUserStatus), v))
	})
}

// UserStatusEqualFold applies the EqualFold predicate on the "UserStatus" field.
func UserStatusEqualFold(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUserStatus), v))
	})
}

// UserStatusContainsFold applies the ContainsFold predicate on the "UserStatus" field.
func UserStatusContainsFold(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUserStatus), v))
	})
}

// HasUserstatusUser applies the HasEdge predicate on the "UserstatusUser" edge.
func HasUserstatusUser() predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserstatusUserTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserstatusUserTable, UserstatusUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserstatusUserWith applies the HasEdge predicate on the "UserstatusUser" edge with a given conditions (other predicates).
func HasUserstatusUserWith(preds ...predicate.User) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserstatusUserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserstatusUserTable, UserstatusUserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
