// Code generated by entc, DO NOT EDIT.

package roomtype

const (
	// Label holds the string label denoting the roomtype type in the database.
	Label = "room_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomType holds the string denoting the roomtype field in the database.
	FieldRoomType = "room_type"
	// FieldCOST holds the string denoting the cost field in the database.
	FieldCOST = "cost"

	// EdgeRoomtypeRoom holds the string denoting the roomtyperoom edge name in mutations.
	EdgeRoomtypeRoom = "RoomtypeRoom"

	// Table holds the table name of the roomtype in the database.
	Table = "room_types"
	// RoomtypeRoomTable is the table the holds the RoomtypeRoom relation/edge.
	RoomtypeRoomTable = "rooms"
	// RoomtypeRoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomtypeRoomInverseTable = "rooms"
	// RoomtypeRoomColumn is the table column denoting the RoomtypeRoom relation/edge.
	RoomtypeRoomColumn = "room_type_roomtype_room"
)

// Columns holds all SQL columns for roomtype fields.
var Columns = []string{
	FieldID,
	FieldRoomType,
	FieldCOST,
}
