// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/PON/app/ent/insurance"
	"github.com/PON/app/ent/rent"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// InsuranceCreate is the builder for creating a Insurance entity.
type InsuranceCreate struct {
	config
	mutation *InsuranceMutation
	hooks    []Hook
}

// SetInsurance sets the Insurance field.
func (ic *InsuranceCreate) SetInsurance(i int) *InsuranceCreate {
	ic.mutation.SetInsurance(i)
	return ic
}

// AddInsuranceRentIDs adds the InsuranceRent edge to Rent by ids.
func (ic *InsuranceCreate) AddInsuranceRentIDs(ids ...int) *InsuranceCreate {
	ic.mutation.AddInsuranceRentIDs(ids...)
	return ic
}

// AddInsuranceRent adds the InsuranceRent edges to Rent.
func (ic *InsuranceCreate) AddInsuranceRent(r ...*Rent) *InsuranceCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ic.AddInsuranceRentIDs(ids...)
}

// Mutation returns the InsuranceMutation object of the builder.
func (ic *InsuranceCreate) Mutation() *InsuranceMutation {
	return ic.mutation
}

// Save creates the Insurance in the database.
func (ic *InsuranceCreate) Save(ctx context.Context) (*Insurance, error) {
	if _, ok := ic.mutation.Insurance(); !ok {
		return nil, &ValidationError{Name: "Insurance", err: errors.New("ent: missing required field \"Insurance\"")}
	}
	var (
		err  error
		node *Insurance
	)
	if len(ic.hooks) == 0 {
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InsuranceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ic.mutation = mutation
			node, err = ic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InsuranceCreate) SaveX(ctx context.Context) *Insurance {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ic *InsuranceCreate) sqlSave(ctx context.Context) (*Insurance, error) {
	i, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	i.ID = int(id)
	return i, nil
}

func (ic *InsuranceCreate) createSpec() (*Insurance, *sqlgraph.CreateSpec) {
	var (
		i     = &Insurance{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: insurance.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: insurance.FieldID,
			},
		}
	)
	if value, ok := ic.mutation.Insurance(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: insurance.FieldInsurance,
		})
		i.Insurance = value
	}
	if nodes := ic.mutation.InsuranceRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   insurance.InsuranceRentTable,
			Columns: []string{insurance.InsuranceRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return i, _spec
}
