// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/PON/app/ent/insurance"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Insurance is the model entity for the Insurance schema.
type Insurance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Insurance holds the value of the "Insurance" field.
	Insurance int `json:"Insurance,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InsuranceQuery when eager-loading is set.
	Edges InsuranceEdges `json:"edges"`
}

// InsuranceEdges holds the relations/edges for other nodes in the graph.
type InsuranceEdges struct {
	// InsuranceRent holds the value of the InsuranceRent edge.
	InsuranceRent []*Rent
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InsuranceRentOrErr returns the InsuranceRent value or an error if the edge
// was not loaded in eager-loading.
func (e InsuranceEdges) InsuranceRentOrErr() ([]*Rent, error) {
	if e.loadedTypes[0] {
		return e.InsuranceRent, nil
	}
	return nil, &NotLoadedError{edge: "InsuranceRent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Insurance) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // Insurance
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Insurance fields.
func (i *Insurance) assignValues(values ...interface{}) error {
	if m, n := len(values), len(insurance.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	i.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Insurance", values[0])
	} else if value.Valid {
		i.Insurance = int(value.Int64)
	}
	return nil
}

// QueryInsuranceRent queries the InsuranceRent edge of the Insurance.
func (i *Insurance) QueryInsuranceRent() *RentQuery {
	return (&InsuranceClient{config: i.config}).QueryInsuranceRent(i)
}

// Update returns a builder for updating this Insurance.
// Note that, you need to call Insurance.Unwrap() before calling this method, if this Insurance
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Insurance) Update() *InsuranceUpdateOne {
	return (&InsuranceClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (i *Insurance) Unwrap() *Insurance {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Insurance is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Insurance) String() string {
	var builder strings.Builder
	builder.WriteString("Insurance(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", Insurance=")
	builder.WriteString(fmt.Sprintf("%v", i.Insurance))
	builder.WriteByte(')')
	return builder.String()
}

// Insurances is a parsable slice of Insurance.
type Insurances []*Insurance

func (i Insurances) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
