// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/PON/app/ent/rent"
	"github.com/PON/app/ent/roomage"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomageCreate is the builder for creating a Roomage entity.
type RoomageCreate struct {
	config
	mutation *RoomageMutation
	hooks    []Hook
}

// SetRoomAge sets the RoomAge field.
func (rc *RoomageCreate) SetRoomAge(i int) *RoomageCreate {
	rc.mutation.SetRoomAge(i)
	return rc
}

// SetText sets the Text field.
func (rc *RoomageCreate) SetText(s string) *RoomageCreate {
	rc.mutation.SetText(s)
	return rc
}

// AddRoomageRentIDs adds the RoomageRent edge to Rent by ids.
func (rc *RoomageCreate) AddRoomageRentIDs(ids ...int) *RoomageCreate {
	rc.mutation.AddRoomageRentIDs(ids...)
	return rc
}

// AddRoomageRent adds the RoomageRent edges to Rent.
func (rc *RoomageCreate) AddRoomageRent(r ...*Rent) *RoomageCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rc.AddRoomageRentIDs(ids...)
}

// Mutation returns the RoomageMutation object of the builder.
func (rc *RoomageCreate) Mutation() *RoomageMutation {
	return rc.mutation
}

// Save creates the Roomage in the database.
func (rc *RoomageCreate) Save(ctx context.Context) (*Roomage, error) {
	if _, ok := rc.mutation.RoomAge(); !ok {
		return nil, &ValidationError{Name: "RoomAge", err: errors.New("ent: missing required field \"RoomAge\"")}
	}
	if _, ok := rc.mutation.Text(); !ok {
		return nil, &ValidationError{Name: "Text", err: errors.New("ent: missing required field \"Text\"")}
	}
	var (
		err  error
		node *Roomage
	)
	if len(rc.hooks) == 0 {
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RoomageCreate) SaveX(ctx context.Context) *Roomage {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rc *RoomageCreate) sqlSave(ctx context.Context) (*Roomage, error) {
	r, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	r.ID = int(id)
	return r, nil
}

func (rc *RoomageCreate) createSpec() (*Roomage, *sqlgraph.CreateSpec) {
	var (
		r     = &Roomage{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: roomage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomage.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.RoomAge(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomage.FieldRoomAge,
		})
		r.RoomAge = value
	}
	if value, ok := rc.mutation.Text(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomage.FieldText,
		})
		r.Text = value
	}
	if nodes := rc.mutation.RoomageRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomage.RoomageRentTable,
			Columns: []string{roomage.RoomageRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return r, _spec
}
