// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PON/app/ent/predicate"
	"github.com/PON/app/ent/rent"
	"github.com/PON/app/ent/room"
	"github.com/PON/app/ent/roomstatus"
	"github.com/PON/app/ent/roomtype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomMutation
	predicates []predicate.Room
}

// Where adds a new predicate for the builder.
func (ru *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetRoomRoomstatusID sets the RoomRoomstatus edge to RoomStatus by id.
func (ru *RoomUpdate) SetRoomRoomstatusID(id int) *RoomUpdate {
	ru.mutation.SetRoomRoomstatusID(id)
	return ru
}

// SetNillableRoomRoomstatusID sets the RoomRoomstatus edge to RoomStatus by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomRoomstatusID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomRoomstatusID(*id)
	}
	return ru
}

// SetRoomRoomstatus sets the RoomRoomstatus edge to RoomStatus.
func (ru *RoomUpdate) SetRoomRoomstatus(r *RoomStatus) *RoomUpdate {
	return ru.SetRoomRoomstatusID(r.ID)
}

// SetRoomRoomtypeID sets the RoomRoomtype edge to RoomType by id.
func (ru *RoomUpdate) SetRoomRoomtypeID(id int) *RoomUpdate {
	ru.mutation.SetRoomRoomtypeID(id)
	return ru
}

// SetNillableRoomRoomtypeID sets the RoomRoomtype edge to RoomType by id if the given value is not nil.
func (ru *RoomUpdate) SetNillableRoomRoomtypeID(id *int) *RoomUpdate {
	if id != nil {
		ru = ru.SetRoomRoomtypeID(*id)
	}
	return ru
}

// SetRoomRoomtype sets the RoomRoomtype edge to RoomType.
func (ru *RoomUpdate) SetRoomRoomtype(r *RoomType) *RoomUpdate {
	return ru.SetRoomRoomtypeID(r.ID)
}

// AddRoomRentIDs adds the RoomRent edge to Rent by ids.
func (ru *RoomUpdate) AddRoomRentIDs(ids ...int) *RoomUpdate {
	ru.mutation.AddRoomRentIDs(ids...)
	return ru
}

// AddRoomRent adds the RoomRent edges to Rent.
func (ru *RoomUpdate) AddRoomRent(r ...*Rent) *RoomUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRoomRentIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (ru *RoomUpdate) Mutation() *RoomMutation {
	return ru.mutation
}

// ClearRoomRoomstatus clears the RoomRoomstatus edge to RoomStatus.
func (ru *RoomUpdate) ClearRoomRoomstatus() *RoomUpdate {
	ru.mutation.ClearRoomRoomstatus()
	return ru
}

// ClearRoomRoomtype clears the RoomRoomtype edge to RoomType.
func (ru *RoomUpdate) ClearRoomRoomtype() *RoomUpdate {
	ru.mutation.ClearRoomRoomtype()
	return ru
}

// RemoveRoomRentIDs removes the RoomRent edge to Rent by ids.
func (ru *RoomUpdate) RemoveRoomRentIDs(ids ...int) *RoomUpdate {
	ru.mutation.RemoveRoomRentIDs(ids...)
	return ru
}

// RemoveRoomRent removes RoomRent edges to Rent.
func (ru *RoomUpdate) RemoveRoomRent(r ...*Rent) *RoomUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRoomRentIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ru.mutation.RoomRoomstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomstatusTable,
			Columns: []string{room.RoomRoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomRoomstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomstatusTable,
			Columns: []string{room.RoomRoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.RoomRoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomtypeTable,
			Columns: []string{room.RoomRoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomRoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomtypeTable,
			Columns: []string{room.RoomRoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := ru.mutation.RemovedRoomRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.RoomRentTable,
			Columns: []string{room.RoomRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.RoomRentTable,
			Columns: []string{room.RoomRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// SetRoomRoomstatusID sets the RoomRoomstatus edge to RoomStatus by id.
func (ruo *RoomUpdateOne) SetRoomRoomstatusID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomRoomstatusID(id)
	return ruo
}

// SetNillableRoomRoomstatusID sets the RoomRoomstatus edge to RoomStatus by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomRoomstatusID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomRoomstatusID(*id)
	}
	return ruo
}

// SetRoomRoomstatus sets the RoomRoomstatus edge to RoomStatus.
func (ruo *RoomUpdateOne) SetRoomRoomstatus(r *RoomStatus) *RoomUpdateOne {
	return ruo.SetRoomRoomstatusID(r.ID)
}

// SetRoomRoomtypeID sets the RoomRoomtype edge to RoomType by id.
func (ruo *RoomUpdateOne) SetRoomRoomtypeID(id int) *RoomUpdateOne {
	ruo.mutation.SetRoomRoomtypeID(id)
	return ruo
}

// SetNillableRoomRoomtypeID sets the RoomRoomtype edge to RoomType by id if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableRoomRoomtypeID(id *int) *RoomUpdateOne {
	if id != nil {
		ruo = ruo.SetRoomRoomtypeID(*id)
	}
	return ruo
}

// SetRoomRoomtype sets the RoomRoomtype edge to RoomType.
func (ruo *RoomUpdateOne) SetRoomRoomtype(r *RoomType) *RoomUpdateOne {
	return ruo.SetRoomRoomtypeID(r.ID)
}

// AddRoomRentIDs adds the RoomRent edge to Rent by ids.
func (ruo *RoomUpdateOne) AddRoomRentIDs(ids ...int) *RoomUpdateOne {
	ruo.mutation.AddRoomRentIDs(ids...)
	return ruo
}

// AddRoomRent adds the RoomRent edges to Rent.
func (ruo *RoomUpdateOne) AddRoomRent(r ...*Rent) *RoomUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRoomRentIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (ruo *RoomUpdateOne) Mutation() *RoomMutation {
	return ruo.mutation
}

// ClearRoomRoomstatus clears the RoomRoomstatus edge to RoomStatus.
func (ruo *RoomUpdateOne) ClearRoomRoomstatus() *RoomUpdateOne {
	ruo.mutation.ClearRoomRoomstatus()
	return ruo
}

// ClearRoomRoomtype clears the RoomRoomtype edge to RoomType.
func (ruo *RoomUpdateOne) ClearRoomRoomtype() *RoomUpdateOne {
	ruo.mutation.ClearRoomRoomtype()
	return ruo
}

// RemoveRoomRentIDs removes the RoomRent edge to Rent by ids.
func (ruo *RoomUpdateOne) RemoveRoomRentIDs(ids ...int) *RoomUpdateOne {
	ruo.mutation.RemoveRoomRentIDs(ids...)
	return ruo
}

// RemoveRoomRent removes RoomRent edges to Rent.
func (ruo *RoomUpdateOne) RemoveRoomRent(r ...*Rent) *RoomUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRoomRentIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {

	var (
		err  error
		node *Room
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomUpdateOne) sqlSave(ctx context.Context) (r *Room, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   room.Table,
			Columns: room.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: room.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Room.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ruo.mutation.RoomRoomstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomstatusTable,
			Columns: []string{room.RoomRoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomRoomstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomstatusTable,
			Columns: []string{room.RoomRoomstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.RoomRoomtypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomtypeTable,
			Columns: []string{room.RoomRoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomRoomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.RoomRoomtypeTable,
			Columns: []string{room.RoomRoomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := ruo.mutation.RemovedRoomRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.RoomRentTable,
			Columns: []string{room.RoomRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.RoomRentTable,
			Columns: []string{room.RoomRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Room{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
