// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/PON/app/ent/predicate"
	"github.com/PON/app/ent/rent"
	"github.com/PON/app/ent/roomage"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoomageUpdate is the builder for updating Roomage entities.
type RoomageUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomageMutation
	predicates []predicate.Roomage
}

// Where adds a new predicate for the builder.
func (ru *RoomageUpdate) Where(ps ...predicate.Roomage) *RoomageUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetRoomAge sets the RoomAge field.
func (ru *RoomageUpdate) SetRoomAge(i int) *RoomageUpdate {
	ru.mutation.ResetRoomAge()
	ru.mutation.SetRoomAge(i)
	return ru
}

// AddRoomAge adds i to RoomAge.
func (ru *RoomageUpdate) AddRoomAge(i int) *RoomageUpdate {
	ru.mutation.AddRoomAge(i)
	return ru
}

// SetText sets the Text field.
func (ru *RoomageUpdate) SetText(s string) *RoomageUpdate {
	ru.mutation.SetText(s)
	return ru
}

// AddRoomageRentIDs adds the RoomageRent edge to Rent by ids.
func (ru *RoomageUpdate) AddRoomageRentIDs(ids ...int) *RoomageUpdate {
	ru.mutation.AddRoomageRentIDs(ids...)
	return ru
}

// AddRoomageRent adds the RoomageRent edges to Rent.
func (ru *RoomageUpdate) AddRoomageRent(r ...*Rent) *RoomageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRoomageRentIDs(ids...)
}

// Mutation returns the RoomageMutation object of the builder.
func (ru *RoomageUpdate) Mutation() *RoomageMutation {
	return ru.mutation
}

// RemoveRoomageRentIDs removes the RoomageRent edge to Rent by ids.
func (ru *RoomageUpdate) RemoveRoomageRentIDs(ids ...int) *RoomageUpdate {
	ru.mutation.RemoveRoomageRentIDs(ids...)
	return ru
}

// RemoveRoomageRent removes RoomageRent edges to Rent.
func (ru *RoomageUpdate) RemoveRoomageRent(r ...*Rent) *RoomageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRoomageRentIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomageUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomageUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomageUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomageUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomage.Table,
			Columns: roomage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomage.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RoomAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomage.FieldRoomAge,
		})
	}
	if value, ok := ru.mutation.AddedRoomAge(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomage.FieldRoomAge,
		})
	}
	if value, ok := ru.mutation.Text(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomage.FieldText,
		})
	}
	if nodes := ru.mutation.RemovedRoomageRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomage.RoomageRentTable,
			Columns: []string{roomage.RoomageRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomageRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomage.RoomageRentTable,
			Columns: []string{roomage.RoomageRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomage.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomageUpdateOne is the builder for updating a single Roomage entity.
type RoomageUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomageMutation
}

// SetRoomAge sets the RoomAge field.
func (ruo *RoomageUpdateOne) SetRoomAge(i int) *RoomageUpdateOne {
	ruo.mutation.ResetRoomAge()
	ruo.mutation.SetRoomAge(i)
	return ruo
}

// AddRoomAge adds i to RoomAge.
func (ruo *RoomageUpdateOne) AddRoomAge(i int) *RoomageUpdateOne {
	ruo.mutation.AddRoomAge(i)
	return ruo
}

// SetText sets the Text field.
func (ruo *RoomageUpdateOne) SetText(s string) *RoomageUpdateOne {
	ruo.mutation.SetText(s)
	return ruo
}

// AddRoomageRentIDs adds the RoomageRent edge to Rent by ids.
func (ruo *RoomageUpdateOne) AddRoomageRentIDs(ids ...int) *RoomageUpdateOne {
	ruo.mutation.AddRoomageRentIDs(ids...)
	return ruo
}

// AddRoomageRent adds the RoomageRent edges to Rent.
func (ruo *RoomageUpdateOne) AddRoomageRent(r ...*Rent) *RoomageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRoomageRentIDs(ids...)
}

// Mutation returns the RoomageMutation object of the builder.
func (ruo *RoomageUpdateOne) Mutation() *RoomageMutation {
	return ruo.mutation
}

// RemoveRoomageRentIDs removes the RoomageRent edge to Rent by ids.
func (ruo *RoomageUpdateOne) RemoveRoomageRentIDs(ids ...int) *RoomageUpdateOne {
	ruo.mutation.RemoveRoomageRentIDs(ids...)
	return ruo
}

// RemoveRoomageRent removes RoomageRent edges to Rent.
func (ruo *RoomageUpdateOne) RemoveRoomageRent(r ...*Rent) *RoomageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRoomageRentIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RoomageUpdateOne) Save(ctx context.Context) (*Roomage, error) {

	var (
		err  error
		node *Roomage
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomageUpdateOne) SaveX(ctx context.Context) *Roomage {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomageUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomageUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomageUpdateOne) sqlSave(ctx context.Context) (r *Roomage, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomage.Table,
			Columns: roomage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomage.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Roomage.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.RoomAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomage.FieldRoomAge,
		})
	}
	if value, ok := ruo.mutation.AddedRoomAge(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomage.FieldRoomAge,
		})
	}
	if value, ok := ruo.mutation.Text(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomage.FieldText,
		})
	}
	if nodes := ruo.mutation.RemovedRoomageRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomage.RoomageRentTable,
			Columns: []string{roomage.RoomageRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomageRentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomage.RoomageRentTable,
			Columns: []string{roomage.RoomageRentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: rent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Roomage{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomage.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
