/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersRent
 */
export interface ControllersRent {
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    cidUser?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    insurance?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    rentAge?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    rentDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    room?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    roomage?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    user?: number;
}

export function ControllersRentFromJSON(json: any): ControllersRent {
    return ControllersRentFromJSONTyped(json, false);
}

export function ControllersRentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersRent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cidUser': !exists(json, 'cidUser') ? undefined : json['cidUser'],
        'insurance': !exists(json, 'insurance') ? undefined : json['insurance'],
        'rentAge': !exists(json, 'rentAge') ? undefined : json['rentAge'],
        'rentDate': !exists(json, 'rentDate') ? undefined : json['rentDate'],
        'room': !exists(json, 'room') ? undefined : json['room'],
        'roomage': !exists(json, 'roomage') ? undefined : json['roomage'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersRentToJSON(value?: ControllersRent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cidUser': value.cidUser,
        'insurance': value.insurance,
        'rentAge': value.rentAge,
        'rentDate': value.rentDate,
        'room': value.room,
        'roomage': value.roomage,
        'user': value.user,
    };
}


