/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRent,
    EntRentFromJSON,
    EntRentFromJSONTyped,
    EntRentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntInsuranceEdges
 */
export interface EntInsuranceEdges {
    /**
     * InsuranceRent holds the value of the InsuranceRent edge.
     * @type {Array<EntRent>}
     * @memberof EntInsuranceEdges
     */
    insuranceRent?: Array<EntRent>;
}

export function EntInsuranceEdgesFromJSON(json: any): EntInsuranceEdges {
    return EntInsuranceEdgesFromJSONTyped(json, false);
}

export function EntInsuranceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntInsuranceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'insuranceRent': !exists(json, 'insuranceRent') ? undefined : ((json['insuranceRent'] as Array<any>).map(EntRentFromJSON)),
    };
}

export function EntInsuranceEdgesToJSON(value?: EntInsuranceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'insuranceRent': value.insuranceRent === undefined ? undefined : ((value.insuranceRent as Array<any>).map(EntRentToJSON)),
    };
}


