/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInsuranceEdges,
    EntInsuranceEdgesFromJSON,
    EntInsuranceEdgesFromJSONTyped,
    EntInsuranceEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntInsurance
 */
export interface EntInsurance {
    /**
     * Insurance holds the value of the "Insurance" field.
     * @type {number}
     * @memberof EntInsurance
     */
    insurance?: number;
    /**
     * 
     * @type {EntInsuranceEdges}
     * @memberof EntInsurance
     */
    edges?: EntInsuranceEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntInsurance
     */
    id?: number;
}

export function EntInsuranceFromJSON(json: any): EntInsurance {
    return EntInsuranceFromJSONTyped(json, false);
}

export function EntInsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntInsurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'insurance': !exists(json, 'Insurance') ? undefined : json['Insurance'],
        'edges': !exists(json, 'edges') ? undefined : EntInsuranceEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntInsuranceToJSON(value?: EntInsurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Insurance': value.insurance,
        'edges': EntInsuranceEdgesToJSON(value.edges),
        'id': value.id,
    };
}


