/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInsurance,
    EntInsuranceFromJSON,
    EntInsuranceFromJSONTyped,
    EntInsuranceToJSON,
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
    EntRoomage,
    EntRoomageFromJSON,
    EntRoomageFromJSONTyped,
    EntRoomageToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRentEdges
 */
export interface EntRentEdges {
    /**
     * 
     * @type {EntInsurance}
     * @memberof EntRentEdges
     */
    rentInsurance?: EntInsurance;
    /**
     * 
     * @type {EntRoom}
     * @memberof EntRentEdges
     */
    rentRoom?: EntRoom;
    /**
     * 
     * @type {EntRoomage}
     * @memberof EntRentEdges
     */
    rentRoomage?: EntRoomage;
    /**
     * 
     * @type {EntUser}
     * @memberof EntRentEdges
     */
    rentUser?: EntUser;
}

export function EntRentEdgesFromJSON(json: any): EntRentEdges {
    return EntRentEdgesFromJSONTyped(json, false);
}

export function EntRentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rentInsurance': !exists(json, 'RentInsurance') ? undefined : EntInsuranceFromJSON(json['RentInsurance']),
        'rentRoom': !exists(json, 'RentRoom') ? undefined : EntRoomFromJSON(json['RentRoom']),
        'rentRoomage': !exists(json, 'RentRoomage') ? undefined : EntRoomageFromJSON(json['RentRoomage']),
        'rentUser': !exists(json, 'RentUser') ? undefined : EntUserFromJSON(json['RentUser']),
    };
}

export function EntRentEdgesToJSON(value?: EntRentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rentInsurance': EntInsuranceToJSON(value.rentInsurance),
        'rentRoom': EntRoomToJSON(value.rentRoom),
        'rentRoomage': EntRoomageToJSON(value.rentRoomage),
        'rentUser': EntUserToJSON(value.rentUser),
    };
}


