/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntUserStatusEdges,
    EntUserStatusEdgesFromJSON,
    EntUserStatusEdgesFromJSONTyped,
    EntUserStatusEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserStatus
 */
export interface EntUserStatus {
    /**
     * UserStatus holds the value of the "UserStatus" field.
     * @type {string}
     * @memberof EntUserStatus
     */
    userStatus?: string;
    /**
     * 
     * @type {EntUserStatusEdges}
     * @memberof EntUserStatus
     */
    edges?: EntUserStatusEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntUserStatus
     */
    id?: number;
}

export function EntUserStatusFromJSON(json: any): EntUserStatus {
    return EntUserStatusFromJSONTyped(json, false);
}

export function EntUserStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userStatus': !exists(json, 'UserStatus') ? undefined : json['UserStatus'],
        'edges': !exists(json, 'edges') ? undefined : EntUserStatusEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntUserStatusToJSON(value?: EntUserStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UserStatus': value.userStatus,
        'edges': EntUserStatusEdgesToJSON(value.edges),
        'id': value.id,
    };
}


