/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRent,
    EntRentFromJSON,
    EntRentFromJSONTyped,
    EntRentToJSON,
    EntUserStatus,
    EntUserStatusFromJSON,
    EntUserStatusFromJSONTyped,
    EntUserStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * UserRent holds the value of the UserRent edge.
     * @type {Array<EntRent>}
     * @memberof EntUserEdges
     */
    userRent?: Array<EntRent>;
    /**
     * 
     * @type {EntUserStatus}
     * @memberof EntUserEdges
     */
    userUserstatus?: EntUserStatus;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userRent': !exists(json, 'userRent') ? undefined : ((json['userRent'] as Array<any>).map(EntRentFromJSON)),
        'userUserstatus': !exists(json, 'userUserstatus') ? undefined : EntUserStatusFromJSON(json['userUserstatus']),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userRent': value.userRent === undefined ? undefined : ((value.userRent as Array<any>).map(EntRentToJSON)),
        'userUserstatus': EntUserStatusToJSON(value.userUserstatus),
    };
}


