// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeRoomRoomstatus holds the string denoting the roomroomstatus edge name in mutations.
	EdgeRoomRoomstatus = "RoomRoomstatus"
	// EdgeRoomRoomtype holds the string denoting the roomroomtype edge name in mutations.
	EdgeRoomRoomtype = "RoomRoomtype"
	// EdgeRoomRent holds the string denoting the roomrent edge name in mutations.
	EdgeRoomRent = "RoomRent"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// RoomRoomstatusTable is the table the holds the RoomRoomstatus relation/edge.
	RoomRoomstatusTable = "rooms"
	// RoomRoomstatusInverseTable is the table name for the RoomStatus entity.
	// It exists in this package in order to avoid circular dependency with the "roomstatus" package.
	RoomRoomstatusInverseTable = "room_status"
	// RoomRoomstatusColumn is the table column denoting the RoomRoomstatus relation/edge.
	RoomRoomstatusColumn = "room_status_roomstatus_room"
	// RoomRoomtypeTable is the table the holds the RoomRoomtype relation/edge.
	RoomRoomtypeTable = "rooms"
	// RoomRoomtypeInverseTable is the table name for the RoomType entity.
	// It exists in this package in order to avoid circular dependency with the "roomtype" package.
	RoomRoomtypeInverseTable = "room_types"
	// RoomRoomtypeColumn is the table column denoting the RoomRoomtype relation/edge.
	RoomRoomtypeColumn = "room_type_roomtype_room"
	// RoomRentTable is the table the holds the RoomRent relation/edge.
	RoomRentTable = "rents"
	// RoomRentInverseTable is the table name for the Rent entity.
	// It exists in this package in order to avoid circular dependency with the "rent" package.
	RoomRentInverseTable = "rents"
	// RoomRentColumn is the table column denoting the RoomRent relation/edge.
	RoomRentColumn = "room_room_rent"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"room_status_roomstatus_room",
	"room_type_roomtype_room",
}
