// Code generated by entc, DO NOT EDIT.

package roomstatus

const (
	// Label holds the string label denoting the roomstatus type in the database.
	Label = "room_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomStatus holds the string denoting the roomstatus field in the database.
	FieldRoomStatus = "room_status"

	// EdgeRoomstatusRoom holds the string denoting the roomstatusroom edge name in mutations.
	EdgeRoomstatusRoom = "RoomstatusRoom"

	// Table holds the table name of the roomstatus in the database.
	Table = "room_status"
	// RoomstatusRoomTable is the table the holds the RoomstatusRoom relation/edge.
	RoomstatusRoomTable = "rooms"
	// RoomstatusRoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomstatusRoomInverseTable = "rooms"
	// RoomstatusRoomColumn is the table column denoting the RoomstatusRoom relation/edge.
	RoomstatusRoomColumn = "room_status_roomstatus_room"
)

// Columns holds all SQL columns for roomstatus fields.
var Columns = []string{
	FieldID,
	FieldRoomStatus,
}
